### ISSUE TITLE
Add travisCI implementation on Slack.

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/plesk_suitecrm#3]

**Comment by ghermans** [comment]
:+1:

**Comment by Tjoosten** [comment]
@ghermand we can do this now?

**Comment by ghermans** [comment]
Sure i will add this tonight.

**Comment by Tjoosten** [comment]
Alright then a will implement slack

**Comment by Tjoosten** [comment]
@ghermans update plz

**Comment by ghermans** [comment]
This project has the lowest priority because i can not publish/export the module from SuiteCRM. this is a bug and the developers are working on it.

**Comment by Tjoosten** [comment]
Closed due inactivity
